# 一 创建张量

In [1]:
# 创建张量
import numpy as np
import tensorflow as tf
x = tf.constant([[1, 2], [3, 4]])
print(x)
print(type(x))
# 下面是0维张量
y = tf.constant(1.0)
print(y)
a = tf.constant(1.0, dtype=tf.float64)
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float64)


In [2]:
b = tf.cast(a, dtype=tf.float32)
print(b)
# 在进行数据类型转换时，一般是将低精度的数据类型向高精度转换，否则可能发生数据溢出，得到错误的结果。
print(tf.constant("hello"))
# b：表示这是一个字节串。
# 在Python3中，字符串默认是Unicode编码，
# 因此要转成字节串，就在原来的字符串前面加上一个b

tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(b'hello', shape=(), dtype=string)


In [3]:
ta = tf.convert_to_tensor(np.arange(12).reshape(3, 4))
print(tf.convert_to_tensor(np.arange(12).reshape(3, 4)))
# is_tensor()函数
print(tf.is_tensor(ta))

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int32)
True


In [4]:
# isinstance()函数
print(isinstance(ta, tf.Tensor))
print(isinstance(np.arange(12).reshape(3, 4), np.ndarray))

True
True


In [5]:
# 创建全0张量和全1张量
print(tf.ones(shape=(2, 1)))
print(tf.ones([6]))
print(tf.ones([2, 3], dtype=tf.int32))

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.Tensor([1. 1. 1. 1. 1. 1.], shape=(6,), dtype=float32)
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [6]:
# 创建元素值都相同的张量—— tf.fill()函数
print(tf.fill([2, 3], 9))
print(tf.fill([2, 3], 9.0))

tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[9. 9. 9.]
 [9. 9. 9.]], shape=(2, 3), dtype=float32)


In [7]:
# 创建元素值都相同的张量—— tf.constant()函数
print(tf.constant(9, shape=[2, 3]))
print(tf.constant(value=9, shape=[2, 3]))
print(tf.fill(dims=[2, 3], value=9))

tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)


In [8]:
# 创建随机数张量————正太分布
# tf.random.normal( shape, mean, stddev, dtype )
# 形状 均值 标准差 数据类型
print(tf.random.normal([2, 3]))
print(tf.random.normal([3, 3, 3], mean=0.0, stddev=2.0))

tf.Tensor(
[[ 0.85437065 -0.27268288  0.17207769]
 [ 1.0141515  -0.4506549  -1.4335564 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[-1.2674005   0.18170622  0.31749362]
  [-1.0799264   1.2521479  -1.0759917 ]
  [-1.2439876  -1.7118998   1.6640587 ]]

 [[-3.0914392  -1.2122856  -1.4664005 ]
  [ 1.3494933   0.61071575  0.5456955 ]
  [ 3.148196    1.8117074  -1.629724  ]]

 [[ 0.80004364  0.55848354 -1.499719  ]
  [ 1.64091     0.96119237 -3.0683405 ]
  [-0.64545125 -1.4589103  -0.97982734]]], shape=(3, 3, 3), dtype=float32)


In [9]:
# 创建随机数张量——截断正态分布
# tf.random.truncated_normal( shape, mean, stddev, dtype )
# 返回一个截断的正态分布
# 截断的标准是2倍的标准差
print(tf.random.truncated_normal([3, 3, 3], mean=0.0, stddev=2.0))

tf.Tensor(
[[[-2.2019253  -3.6187997   0.23775092]
  [ 2.405262    1.3926837  -0.674369  ]
  [-2.738942    0.782003   -1.4810795 ]]

 [[ 0.423615   -0.27247962 -0.66910815]
  [ 2.0796607   2.454543    0.75386316]
  [-1.8743974  -1.1681387  -1.6842493 ]]

 [[-2.8563197  -1.7903223   3.6983726 ]
  [-1.2442654   0.6759736   0.30835837]
  [ 1.136205    3.2292755  -0.49517477]]], shape=(3, 3, 3), dtype=float32)


In [10]:
# 设置随机种子——tf.random.set_seed()函数
tf.random.set_seed(8)
print(tf.random.normal([2, 2]))
tf.random.set_seed(8)
print(tf.random.normal([2, 2]))

tf.Tensor(
[[ 1.2074401  -0.7452463 ]
 [ 0.6908678  -0.76359874]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.2074401  -0.7452463 ]
 [ 0.6908678  -0.76359874]], shape=(2, 2), dtype=float32)


In [11]:
# 创建均匀分布张量——tf.random.uniform()函数
print(tf.random.uniform([2, 3], minval=8, maxval=11, dtype=tf.float32))

tf.Tensor(
[[ 8.71581   8.868814  8.278814]
 [10.282644 10.891918 10.831882]], shape=(2, 3), dtype=float32)


In [12]:
# 随机打乱——tf.random.shuffle()函数
xx = tf.constant([[1, 2], [3, 4], [5, 6]])
# 参数为张量 列表 数组，随机打乱第一维
yy = tf.random.shuffle(x)
print(x)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [13]:
# 创建序列——tf.range()函数
print(tf.range(start=8, limit=18, delta=1, dtype=tf.float32))
print(tf.range(start=8, limit=18, delta=2, dtype=tf.float32))

tf.Tensor([ 8.  9. 10. 11. 12. 13. 14. 15. 16. 17.], shape=(10,), dtype=float32)
tf.Tensor([ 8. 10. 12. 14. 16.], shape=(5,), dtype=float32)


In [14]:
# Tensor对象的属性——ndim、shape、dtype
xxx = tf.random.normal(shape=[2, 3], mean=0.0, stddev=2.0)
print("ndim:", xxx.ndim)
print("shape:", xxx.shape)
print("dtype:", xxx.dtype)

ndim: 2
shape: (2, 3)
dtype: <dtype: 'float32'>


In [15]:
# 获得Tensor对象的形状、元素总数和维度
print(tf.shape(xxx))
print(tf.size(xxx))
print(tf.rank(xxx))

tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


# 二 维度变换
## 2.1 张量的存储和视图
+ 多维张量在物理上以一维的方式连续存储，通过定义维度和形状，在逻辑上把它理解为多维张量
+ 当对多维张量进行维度变换时，只是改变了逻辑上索引的方式，没有改变内存中的存储方式
## 改变张量的形状

In [16]:
print(tf.reshape(xxx, [6, 1]))
print(np.arange(24).reshape(2, 3, 4))

tf.Tensor(
[[-0.30076715]
 [-0.2935319 ]
 [-0.6010592 ]
 [-2.7288115 ]
 [ 2.2710328 ]
 [-1.1560678 ]], shape=(6, 1), dtype=float32)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## 2.2 增加和删除维度

In [24]:
t = tf.constant([1, 2])
print(t.shape)
t

(2,)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

### 2.2.1 增加维度

In [21]:
t1 = tf.expand_dims(t, 1)
print(t1.shape)
t1

(2, 1)


<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [2]])>

In [34]:
t2 = tf.expand_dims(t, 0)
print(t2.shape)
print(t2)

t3 = tf.expand_dims(t2, 0)
print(t3.shape)
print(t3)

(1, 2)
tf.Tensor([[1 2]], shape=(1, 2), dtype=int32)
(1, 1, 2)
tf.Tensor([[[1 2]]], shape=(1, 1, 2), dtype=int32)


In [35]:
t4 = tf.expand_dims(t, -1)
print(t4.shape)
print(t4)

(2, 1)
tf.Tensor(
[[1]
 [2]], shape=(2, 1), dtype=int32)


### 2.2.2 删除维度
+ 只能删除长度为 1 的维度，省略时删除所有长度为1的维度

In [47]:
tt = tf.constant(np.arange(6))
tt = tf.reshape(tt, [1, 2, 1, 3, 1])
print(tt.shape)
print(tf.shape(tf.squeeze(tt)))
print(tt.shape)

print(tf.shape(tf.squeeze(tt, axis=[2, 4])))

(1, 2, 1, 3, 1)
tf.Tensor([2 3], shape=(2,), dtype=int32)
(1, 2, 1, 3, 1)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


+ 增加维度和删除维度，只是改变了张量的视图，不会改变张量的存储

## 2.3 交换维度
+ 对二维张量交换维度，就是矩阵的转置

In [48]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
print(tf.transpose(x))

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


+ 调整张量中各个轴的顺序
+ 改变轴的顺序，从而改变张量的形状

In [49]:
print(tf.transpose(x, perm=[1, 0]))

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


+ 交换维度，不仅改变了张量的视图，同时也改变了张量的存储顺序

## 2.4 拼接和分割
### 2.4.1 拼接张量
+ 将多个张量在某个维度上合并
+ 拼接并不会产生新的维度

In [56]:
t1 = tf.reshape(tf.range(1, 7), shape=[2, 3])
t2 = tf.reshape(tf.range(7, 13), shape=[2, 3])
print(tf.concat([t1, t2], axis=0))

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)


### 2.4.2 分割张量：将一个张量拆分成多个张量，分割后维度不变
+ tf.split( value, num_or_size_splits, axis=0 )
+ value=待分割张量, num_or_size_splits=分割方案, axis=指明分割的轴
+ 分割方案：是一个数值时，表示等长分割，数值是切割的份数；是一个列表时，表示不等长切割，列表中是切割后每份的长度

In [58]:
x = tf.reshape(tf.range(24), shape=[4, 6])
print(tf.split(x, num_or_size_splits=2, axis=0))

[<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])>, <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])>]


+ 图像的分割与拼接，改变了张量的视图，张量的存储顺序并没有改变。

## 2.5 堆叠和分解
### 2.5.1 堆叠张量
+ 在合并张量时，创建一个新的维度
+ 和NumPy中堆叠函数的功能完全一样

In [60]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
print(tf.stack((x, y), axis=0))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


### 2.5.2 分解张量
+ 是张量堆叠的逆运算
+ 张量分解为多个张量
+ 分解后得到的每个张 量，和原来的张量相比，维数都少了一维

In [61]:
c = tf.stack((x, y), axis=0)
print(tf.unstack(c, axis=1))

[<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4])>, <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5])>, <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 6])>]


# 三 部分采样

## 数据提取 根据索引，抽取出没有规律的、特定的数据
+ `gather()`函数：用一个索引列表，将给定张量中对应索引值的元素提取出来

In [62]:
a = tf.range(5)
print(tf.gather(a, indices=[0, 2, 3]))

tf.Tensor([0 2 3], shape=(3,), dtype=int32)


+ 对多维张量采样——`gather()、gather_nd()`函数

In [63]:
a = tf.range(20)
a = tf.reshape(a, shape=[4, 5])
print(tf.gather(a, axis=0, indices=[0, 2, 3]))

tf.Tensor(
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]], shape=(3, 5), dtype=int32)


+ 同时采样多个点——`gather_nd()`函数

In [64]:
print(tf.gather_nd(a, [[0, 1], [1, 1], [2, 3]]))

tf.Tensor([ 1  6 13], shape=(3,), dtype=int32)


# 四 张量运算

## 4.1 基本数学运算

| 算术操作 | 描述 |
|---------| ----- |
|tf.add(x, y)|将x和y逐元素相加|
|tf.subtract(x, y)|将x和y逐元素相减|
|tf.multiply(x, y)|将x和y逐元素相乘|
|tf.divide(x, y)|将x和y逐元素相除|
|tf.math.mod(x, y)|对x元素取模|